import Head from 'next/head'
import { Container , Button , Col , Row , Alert } from 'react-bootstrap' 
import LazyHero from 'react-lazy-hero'
// import { IconName } from "react-icons"

export default function Home() {
  let  Meta = () => (
  <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
  </Head>
  )

  return (
    <Container>
      <Meta/>
    </Container>
   
  )
}

